#!/usr/bin/env ruby

require_relative 'classes/app'

def display_menu
  puts "\n\nPlease choose an option by entering a number:"
  puts '1 - List all books'
  puts '2 - List all people'
  puts '3 - Create a person'
  puts '4 - Create a book'
  puts '5 - Create a rental'
  puts '6 - List all rentals for a given person id'
  puts '7 - Exit'
end

def execute_menu_options(app, option)
  puts "\n"
  case option
  when 1
    app.list_books
  when 2
    app.list_people
  when 3
    app.create_person
  when 4
    app.create_book
  when 5
    app.create_rental
  when 6
    app.list_rentals
  end
end

def main
  app = App.new
  option = 0
  while option != 7
    display_menu
    print '[Input the number]: '
    option = gets.chomp.to_i
    execute_menu_options(app, option) if option >= 1 && option <= 6
  end
  app.persist_data
  puts "Thank you for using this app!\n\n"
end

main
